name: flutter_local_notifications_linux
publish_to: none
description: Linux implementation of the flutter_local_notifications plugin
version: 4.0.0+1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

dependencies:
  dbus: ^0.7.8
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: 
    git: https://github.com/kumsumit/flutter_local_notifications_platform_interface.git
  path: ^1.8.3
  xdg_directories: 
    git: https://github.com/kumsumit/xdg_directories.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.1.0"
